# Generated by Django 2.2.7 on 2019-11-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_education', models.CharField(blank=True, max_length=100, null=True, verbose_name='Educação - Meta')),
                ('donation_link_education', models.CharField(blank=True, max_length=300, null=True, verbose_name='Link para vaquinha - Educação')),
                ('title_health', models.CharField(blank=True, max_length=100, null=True, verbose_name='Saúde - Meta')),
                ('donation_link_health', models.CharField(blank=True, max_length=300, null=True, verbose_name='Link para vaquinha - Saúde')),
                ('title_entrepreneur', models.CharField(blank=True, max_length=100, null=True, verbose_name='População Empreendedora - Meta')),
                ('donation_link_entrepreneur', models.CharField(blank=True, max_length=300, null=True, verbose_name='Link para vaquinha - População Empreendedora')),
                ('title_welfare', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bem-estar Social - Meta')),
                ('donation_link_welfare', models.CharField(blank=True, max_length=300, null=True, verbose_name='Link para vaquinha - Bem-estar social')),
            ],
            options={
                'verbose_name': 'Metas',
            },
        ),
    ]
