# Generated by Django 2.2.7 on 2019-11-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_metas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcoHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='timeline/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Marco Histórico',
                'verbose_name_plural': 'Marcos Históricos',
            },
        ),
    ]
